version: 2
updates:
  # Eliminar el bloque 'npm' si no tienes package.json
  
  # Dejar SOLO si usas GitHub Actions para CI/CD (despliegue, testing, etc.)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
